# config/services.yaml
parameters:
  oauth.oidc.client_id: "###"
  oauth.oidc.client_secret: "###"
  oauth.oidc.auth_server_url: "###"
  oauth.oidc.realm: "###"
  oauth.oidc.secured_frontend: "false"
  oauth.oidc.secured: "false"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ "setFramework", [ "@contao.framework" ] ]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ "setContainer", [ "@service_container" ] ]
  ronnybremer\OAuthBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]
  oidc_authenticator:
    class: ronnybremer\OAuthBundle\Security\OidcAuthenticator
    arguments: ["@contao.framework", "@knpu.oauth2.registry"]
    autowire: true
  ronnybremer\OAuthBundle\Controller\KeycloakController:
    arguments: ["@knpu.oauth2.registry"]
